name: Release

on:
  - push

jobs:
  sanitycheck:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run vet
        run: |
          go vet .
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: sanitycheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          MAJOR_STRING_TOKEN: "major:"
          MINOR_STRING_TOKEN: "minor:"
          PATCH_STRING_TOKEN: "patch:"

      - name: Create Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          token: ${{ secrets.RELEASE_TOKEN }}